# Generated by Django 5.2.6 on 2025-09-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_update_task_definition_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdefinition",
            name="task_target",
            field=models.CharField(
                choices=[("stock_data_update", "股票数据更新"), ("ai_analysis", "AI分析")],
                max_length=50,
                verbose_name="任务目标",
            ),
        ),
    ]
