# Generated by Django 5.2.6 on 2025-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_taskdefinition_task_target"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataupdatetask",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("stock_basic", "股票基础信息"),
                    ("stock_realtime", "股票实时数据"),
                    ("stock_history", "股票历史数据"),
                    ("stock_minute", "股票分时数据"),
                    ("stock_history_qfq", "历史数据-前复权"),
                    ("market_realtime", "大盘实时数据"),
                    ("market_history", "大盘历史数据"),
                    ("industry_data", "行业数据"),
                    ("concept_data", "概念数据"),
                    ("money_flow", "资金流向"),
                    ("dragon_tiger", "龙虎榜"),
                    ("margin_trading", "两融数据"),
                ],
                max_length=30,
                verbose_name="数据类型",
            ),
        ),
    ]
