# Generated by Django 5.2.6 on 2025-09-15 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_dataupdatetask_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.taskdefinition",
                verbose_name="关联任务",
            ),
        ),
    ]
