# Generated by Django 5.2.6 on 2025-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiinterface",
            name="purposes",
            field=models.JSONField(blank=True, default=list, verbose_name="接口用途"),
        ),
    ]
