# Generated by Django 5.2.6 on 2025-09-11 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConceptInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept_code",
                    models.CharField(max_length=20, unique=True, verbose_name="概念代码"),
                ),
                ("concept_name", models.CharField(max_length=50, verbose_name="概念名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "概念板块信息",
                "verbose_name_plural": "概念板块信息",
                "db_table": "concept_info",
                "ordering": ["concept_code"],
            },
        ),
        migrations.CreateModel(
            name="MarketIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_code",
                    models.CharField(max_length=10, unique=True, verbose_name="指数代码"),
                ),
                ("index_name", models.CharField(max_length=50, verbose_name="指数名称")),
                (
                    "market",
                    models.CharField(
                        choices=[("SH", "上海证券交易所"), ("SZ", "深圳证券交易所"), ("CSI", "中证指数")],
                        max_length=10,
                        verbose_name="交易所",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "大盘指数",
                "verbose_name_plural": "大盘指数",
                "db_table": "market_index",
                "ordering": ["index_code"],
            },
        ),
        migrations.CreateModel(
            name="StockCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("stock_name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("earnings", "业绩发布"),
                            ("dividend", "分红派息"),
                            ("meeting", "股东大会"),
                            ("ipo", "新股上市"),
                            ("suspension", "停牌复牌"),
                            ("other", "其他事件"),
                        ],
                        max_length=20,
                        verbose_name="事件类型",
                    ),
                ),
                ("event_title", models.CharField(max_length=100, verbose_name="事件标题")),
                ("event_content", models.TextField(verbose_name="事件内容")),
                ("event_date", models.DateField(verbose_name="事件日期")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="是否重要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "股票日历",
                "verbose_name_plural": "股票日历",
                "db_table": "stock_calendar",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="DragonTigerList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("stock_name", models.CharField(max_length=50, verbose_name="股票名称")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="换手率(%)"
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="净买额"
                    ),
                ),
                (
                    "buy_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="买入额"
                    ),
                ),
                (
                    "sell_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="卖出额"
                    ),
                ),
                ("reason", models.CharField(max_length=100, verbose_name="上榜原因")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "龙虎榜数据",
                "verbose_name_plural": "龙虎榜数据",
                "db_table": "dragon_tiger_list",
                "ordering": ["-trade_date", "-net_amount"],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="IndustryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "industry_code",
                    models.CharField(max_length=20, unique=True, verbose_name="行业代码"),
                ),
                ("industry_name", models.CharField(max_length=50, verbose_name="行业名称")),
                ("level", models.IntegerField(default=1, verbose_name="层级")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent_industry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market.industryinfo",
                        verbose_name="父级行业",
                    ),
                ),
            ],
            options={
                "verbose_name": "行业板块信息",
                "verbose_name_plural": "行业板块信息",
                "db_table": "industry_info",
                "ordering": ["industry_code"],
            },
        ),
        migrations.CreateModel(
            name="MarginTradingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("stock_name", models.CharField(max_length=50, verbose_name="股票名称")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "margin_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="融资余额"
                    ),
                ),
                (
                    "margin_buy_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="融资买入额"
                    ),
                ),
                (
                    "margin_repay_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="融资偿还额"
                    ),
                ),
                (
                    "short_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="融券余额"
                    ),
                ),
                ("short_sell_volume", models.BigIntegerField(verbose_name="融券卖出量")),
                ("short_repay_volume", models.BigIntegerField(verbose_name="融券偿还量")),
                (
                    "total_balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="融资融券余额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "两融数据",
                "verbose_name_plural": "两融数据",
                "db_table": "margin_trading_data",
                "ordering": ["-trade_date"],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="MoneyFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("market", "大盘资金流向"),
                            ("industry", "行业资金流向"),
                            ("concept", "概念资金流向"),
                            ("stock", "个股资金流向"),
                        ],
                        max_length=20,
                        verbose_name="流向类型",
                    ),
                ),
                ("target_code", models.CharField(max_length=20, verbose_name="目标代码")),
                ("target_name", models.CharField(max_length=50, verbose_name="目标名称")),
                (
                    "main_net_inflow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="主力净流入"
                    ),
                ),
                (
                    "super_large_net_inflow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="超大单净流入"
                    ),
                ),
                (
                    "large_net_inflow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="大单净流入"
                    ),
                ),
                (
                    "medium_net_inflow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="中单净流入"
                    ),
                ),
                (
                    "small_net_inflow",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="小单净流入"
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "资金流向",
                "verbose_name_plural": "资金流向",
                "db_table": "money_flow",
                "ordering": ["-trade_date"],
                "unique_together": {("flow_type", "target_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="ConceptRealtimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="平均价格"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("up_count", models.IntegerField(verbose_name="上涨家数")),
                ("down_count", models.IntegerField(verbose_name="下跌家数")),
                ("flat_count", models.IntegerField(verbose_name="平盘家数")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="总成交额"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="数据时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.conceptinfo",
                        verbose_name="概念",
                    ),
                ),
            ],
            options={
                "verbose_name": "概念实时数据",
                "verbose_name_plural": "概念实时数据",
                "db_table": "concept_realtime_data",
                "ordering": ["-timestamp"],
                "unique_together": {("concept", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="IndustryRealtimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="平均价格"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("up_count", models.IntegerField(verbose_name="上涨家数")),
                ("down_count", models.IntegerField(verbose_name="下跌家数")),
                ("flat_count", models.IntegerField(verbose_name="平盘家数")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="总成交额"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="数据时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.industryinfo",
                        verbose_name="行业",
                    ),
                ),
            ],
            options={
                "verbose_name": "行业实时数据",
                "verbose_name_plural": "行业实时数据",
                "db_table": "industry_realtime_data",
                "ordering": ["-timestamp"],
                "unique_together": {("industry", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="MarketHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="开盘点位"
                    ),
                ),
                (
                    "high_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高点位"
                    ),
                ),
                (
                    "low_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低点位"
                    ),
                ),
                (
                    "close_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="收盘点位"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="昨收点位"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌点数"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.marketindex",
                        verbose_name="指数",
                    ),
                ),
            ],
            options={
                "verbose_name": "大盘历史数据",
                "verbose_name_plural": "大盘历史数据",
                "db_table": "market_history_data",
                "ordering": ["-trade_date"],
                "unique_together": {("index", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="MarketRealtimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="当前点位"
                    ),
                ),
                (
                    "open_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="开盘点位"
                    ),
                ),
                (
                    "high_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高点位"
                    ),
                ),
                (
                    "low_point",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低点位"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="昨收点位"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌点数"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="数据时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.marketindex",
                        verbose_name="指数",
                    ),
                ),
            ],
            options={
                "verbose_name": "大盘实时数据",
                "verbose_name_plural": "大盘实时数据",
                "db_table": "market_realtime_data",
                "ordering": ["-timestamp"],
                "unique_together": {("index", "timestamp")},
            },
        ),
    ]
