# Generated by Django 5.2.6 on 2025-09-11 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(max_length=10, unique=True, verbose_name="股票代码"),
                ),
                ("stock_name", models.CharField(max_length=50, verbose_name="股票名称")),
                (
                    "market",
                    models.CharField(
                        choices=[
                            ("SH", "上海证券交易所"),
                            ("SZ", "深圳证券交易所"),
                            ("BJ", "北京证券交易所"),
                        ],
                        max_length=10,
                        verbose_name="交易所",
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=50, verbose_name="所属行业"),
                ),
                ("concept", models.TextField(blank=True, verbose_name="概念板块")),
                (
                    "list_date",
                    models.DateField(blank=True, null=True, verbose_name="上市日期"),
                ),
                (
                    "total_share",
                    models.BigIntegerField(blank=True, null=True, verbose_name="总股本"),
                ),
                (
                    "float_share",
                    models.BigIntegerField(blank=True, null=True, verbose_name="流通股本"),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="总市值",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票基础信息",
                "verbose_name_plural": "股票基础信息",
                "db_table": "stock_basic_info",
                "ordering": ["stock_code"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_up", "价格上涨"),
                            ("price_down", "价格下跌"),
                            ("volume_surge", "成交量异动"),
                            ("change_pct", "涨跌幅异动"),
                        ],
                        max_length=20,
                        verbose_name="提醒类型",
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="阈值"
                    ),
                ),
                (
                    "is_triggered",
                    models.BooleanField(default=False, verbose_name="是否已触发"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="触发时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockbasicinfo",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票提醒",
                "verbose_name_plural": "股票提醒",
                "db_table": "stock_alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="昨收价"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockbasicinfo",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票历史数据",
                "verbose_name_plural": "股票历史数据",
                "db_table": "stock_history_data",
                "ordering": ["-trade_date"],
                "unique_together": {("stock", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="StockMinuteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                ("minute_time", models.TimeField(verbose_name="分时时间")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockbasicinfo",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票分时数据",
                "verbose_name_plural": "股票分时数据",
                "db_table": "stock_minute_data",
                "ordering": ["-trade_date", "-minute_time"],
                "unique_together": {("stock", "trade_date", "minute_time")},
            },
        ),
        migrations.CreateModel(
            name="StockRealtimeData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="当前价格"
                    ),
                ),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="最低价"
                    ),
                ),
                (
                    "pre_close",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="昨收价"
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=4, max_digits=8, verbose_name="涨跌幅(%)"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="市盈率",
                    ),
                ),
                (
                    "pb_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="市净率",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="数据时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockbasicinfo",
                        verbose_name="股票",
                    ),
                ),
            ],
            options={
                "verbose_name": "股票实时数据",
                "verbose_name_plural": "股票实时数据",
                "db_table": "stock_realtime_data",
                "ordering": ["-timestamp"],
                "unique_together": {("stock", "timestamp")},
            },
        ),
        migrations.CreateModel(
            name="WatchList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="添加时价格",
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="目标价格",
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="止损价格",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stockbasicinfo",
                        verbose_name="股票",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "自选股票",
                "verbose_name_plural": "自选股票",
                "db_table": "watch_list",
                "ordering": ["-created_at"],
                "unique_together": {("stock", "user")},
            },
        ),
    ]
