# Generated by Django 5.2.6 on 2025-09-11 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        # Table already created manually, this migration marks it as applied
        migrations.RunSQL(
            "SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",  # No-op reverse SQL
        ),
    ]
