# Generated by Django 5.2.6 on 2025-09-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_auto_20250911_2323"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockDailyHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最低价"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="涨跌幅(%)",
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="涨跌额(元)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "task_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务开始时间"),
                ),
                (
                    "task_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票每日历史数据",
                "verbose_name_plural": "股票每日历史数据",
                "db_table": "stock_daily_history_data",
                "ordering": ["-trade_date"],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="StockMonthlyHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最低价"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="涨跌幅(%)",
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="涨跌额(元)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "task_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务开始时间"),
                ),
                (
                    "task_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票每月历史数据",
                "verbose_name_plural": "股票每月历史数据",
                "db_table": "stock_monthly_history_data",
                "ordering": ["-trade_date"],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
        migrations.CreateModel(
            name="StockWeeklyHistoryData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_code", models.CharField(max_length=10, verbose_name="股票代码")),
                ("trade_date", models.DateField(verbose_name="交易日期")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="开盘价"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="收盘价"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最高价"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="最低价"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量(手)")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="成交额(元)"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="振幅(%)",
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="涨跌幅(%)",
                    ),
                ),
                (
                    "change_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="涨跌额(元)",
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="换手率(%)",
                    ),
                ),
                (
                    "task_start_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务开始时间"),
                ),
                (
                    "task_end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="任务结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "股票每周历史数据",
                "verbose_name_plural": "股票每周历史数据",
                "db_table": "stock_weekly_history_data",
                "ordering": ["-trade_date"],
                "unique_together": {("stock_code", "trade_date")},
            },
        ),
    ]
