# Generated by Django 5.2.6 on 2025-09-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_alter_watchlist_unique_together_watchlist_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdailyhistorydata",
            name="amplitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="振幅(%)",
            ),
        ),
        migrations.AlterField(
            model_name="stockmonthlyhistorydata",
            name="amplitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="振幅(%)",
            ),
        ),
        migrations.AlterField(
            model_name="stockweeklyhistorydata",
            name="amplitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="振幅(%)",
            ),
        ),
    ]
