# Generated by Django 5.2.6 on 2025-09-11 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="模型名称"),
                ),
                ("api_key", models.CharField(max_length=200, verbose_name="API密钥")),
                ("base_url", models.URLField(verbose_name="API基础URL")),
                ("model_name", models.CharField(max_length=100, verbose_name="模型标识")),
                ("max_tokens", models.IntegerField(default=4000, verbose_name="最大令牌数")),
                ("temperature", models.FloatField(default=0.7, verbose_name="温度参数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI模型配置",
                "verbose_name_plural": "AI模型配置",
                "db_table": "ai_model_configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnalysisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("stock", "股票分析"),
                            ("market", "市场分析"),
                            ("technical", "技术分析"),
                            ("sentiment", "情绪分析"),
                        ],
                        max_length=20,
                        verbose_name="分析类型",
                    ),
                ),
                (
                    "stock_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="股票代码"
                    ),
                ),
                ("prompt", models.TextField(verbose_name="分析提示")),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="分析结果"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI分析记录",
                "verbose_name_plural": "AI分析记录",
                "db_table": "ai_analysis_records",
                "ordering": ["-created_at"],
            },
        ),
    ]
